server:
  port: 8090

spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/splashcan
    username: splashcan
    password: splashcan
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  swagger-ui:
    path: /swagger-ui.html
